name: Build & Release Oraxen

on:
  push:
    tags:
      - 'v*'  # Sadece v1.0.0 gibi etiketli pushlarda çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo klonlanıyor
        uses: actions/checkout@v3

      - name: Java 21 kuruluyor
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle önbellekleme
        uses: gradle/gradle-build-action@v2

      - name: Derleme başlatılıyor
        run: ./gradlew build

      - name: JAR dosyasını bul
        id: find_jar
        run: |
          echo "artifact_path=$(find . -type f -name '*.jar' -path '*/build/libs/*' | head -n 1)" >> $GITHUB_OUTPUT

      - name: GitHub Releases’a yükle
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find_jar.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
